global:
  sendAnonymousUsage: false

log:
  level: INFO
  format: common

providers:
  file:
    directory: /dynamic/
    watch: true
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: true
    swarmMode: false

api:
  dashboard: true
  debug: false
  insecure: true

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: false
  https:
    address: :443
  node:
    address: :3000
  mysql:
    address: :3306
